# Generated by Django 3.1.7 on 2021-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogish', '0002_auto_20210301_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True),
        ),
    ]
